echo "clean:clean
	 clean:help
	 compiler:compile
	 compiler:testCompile
	 compiler:help
	 deploy:deploy
	 deploy:deploy-file
	 deploy:help
	 install:install
	 install:install-file
	 install:help
	 resources:resources
	 resources:testResources
	 resources:copy-resources
	 resources:help
	 site:site
	 site:deploy
	 site:run
	 site:stage
	 site:stage-deploy
	 site:attach-descriptor
	 site:jar
	 site:help
	 surefire:test
	 surefire:help
	 verifier:verify
	 verifier:help"